# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_translatable}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Walter McGinnis"]
  s.date = %q{2010-04-13}
  s.description = %q{Rails specific I18n model localization meant to tie-in to existing ActiveRecord models, ala Globalize2, backed by MongoDB rather than an RDBMS. May include UI elements, too.}
  s.email = %q{walter@katipo.co.nz}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/translations_controller.rb",
     "app/helpers/translations_helper.rb",
     "app/views/translations/_form.html.erb",
     "app/views/translations/_translatable_value.html.erb",
     "app/views/translations/_translation_field.html.erb",
     "app/views/translations/edit.html.erb",
     "app/views/translations/index.html.erb",
     "app/views/translations/new.html.erb",
     "app/views/translations/show.html.erb",
     "config/locales/en.yml",
     "lib/mongo_translatable.rb",
     "rails/init.rb",
     "test/database.yml",
     "test/factories.rb",
     "test/functional/test_translations_controller.rb",
     "test/helper.rb",
     "test/integration/test_translations.rb",
     "test/schema.rb",
     "test/test_mongo_translatable.rb",
     "test/unit/helpers/test_translations_helper.rb"
  ]
  s.homepage = %q{http://github.com/kete/mongo_translatable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{MongoDB backed Rails specific I18n model localization meant to tie-in to existing ActiveRecord models}
  s.test_files = [
    "test/factories.rb",
     "test/functional/test_translations_controller.rb",
     "test/helper.rb",
     "test/integration/test_translations.rb",
     "test/schema.rb",
     "test/test_mongo_translatable.rb",
     "test/unit/helpers/test_translations_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.7.3"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_development_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_development_dependency(%q<webrat>, [">= 0.5.3"])
    else
      s.add_dependency(%q<mongo_mapper>, [">= 0.7.3"])
      s.add_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_dependency(%q<webrat>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<mongo_mapper>, [">= 0.7.3"])
    s.add_dependency(%q<activerecord>, [">= 2.3.5"])
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
    s.add_dependency(%q<webrat>, [">= 0.5.3"])
  end
end

