# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongo_translatable}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Walter McGinnis"]
  s.date = %q{2010-05-04}
  s.description = %q{Rails specific I18n model localization meant to tie-in to existing ActiveRecord models, ala Globalize2, backed by MongoDB rather than an RDBMS. May include UI elements, too.}
  s.email = %q{walter@katipo.co.nz}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitmodules",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/translations_controller.rb",
     "app/helpers/translations_helper.rb",
     "app/views/layouts/translations.html.erb",
     "app/views/translations/_form.html.erb",
     "app/views/translations/_translatable_value.html.erb",
     "app/views/translations/_translation_field.html.erb",
     "app/views/translations/edit.html.erb",
     "app/views/translations/index.html.erb",
     "app/views/translations/new.html.erb",
     "app/views/translations/show.html.erb",
     "config/locales/en.yml",
     "config/locales/fr.yml",
     "lib/mongo_translatable.rb",
     "lib/translatables_helper.rb",
     "lib/translations_controller_helpers.rb",
     "mongo_translatable.gemspec",
     "rails/init.rb",
     "test/full_2_3_5_app_with_tests/.gitignore",
     "test/full_2_3_5_app_with_tests/README",
     "test/full_2_3_5_app_with_tests/Rakefile",
     "test/full_2_3_5_app_with_tests/app/controllers/application_controller.rb",
     "test/full_2_3_5_app_with_tests/app/controllers/items_controller.rb",
     "test/full_2_3_5_app_with_tests/app/helpers/application_helper.rb",
     "test/full_2_3_5_app_with_tests/app/helpers/items_helper.rb",
     "test/full_2_3_5_app_with_tests/app/models/item.rb",
     "test/full_2_3_5_app_with_tests/app/views/items/edit.html.erb",
     "test/full_2_3_5_app_with_tests/app/views/items/index.html.erb",
     "test/full_2_3_5_app_with_tests/app/views/items/new.html.erb",
     "test/full_2_3_5_app_with_tests/app/views/items/show.html.erb",
     "test/full_2_3_5_app_with_tests/app/views/layouts/items.html.erb",
     "test/full_2_3_5_app_with_tests/config/boot.rb",
     "test/full_2_3_5_app_with_tests/config/database.yml",
     "test/full_2_3_5_app_with_tests/config/environment.rb",
     "test/full_2_3_5_app_with_tests/config/environments/development.rb",
     "test/full_2_3_5_app_with_tests/config/environments/production.rb",
     "test/full_2_3_5_app_with_tests/config/environments/test.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/backtrace_silencers.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/inflections.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/mime_types.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/new_rails_defaults.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/session_store.rb",
     "test/full_2_3_5_app_with_tests/config/locales.yml",
     "test/full_2_3_5_app_with_tests/config/locales/en.yml",
     "test/full_2_3_5_app_with_tests/config/locales/fr.yml",
     "test/full_2_3_5_app_with_tests/config/locales/zh.yml",
     "test/full_2_3_5_app_with_tests/config/routes.rb",
     "test/full_2_3_5_app_with_tests/db/migrate/20100407010602_create_items.rb",
     "test/full_2_3_5_app_with_tests/db/schema.rb",
     "test/full_2_3_5_app_with_tests/db/seeds.rb",
     "test/full_2_3_5_app_with_tests/doc/README_FOR_APP",
     "test/full_2_3_5_app_with_tests/log/production.log",
     "test/full_2_3_5_app_with_tests/log/server.log",
     "test/full_2_3_5_app_with_tests/public/404.html",
     "test/full_2_3_5_app_with_tests/public/422.html",
     "test/full_2_3_5_app_with_tests/public/500.html",
     "test/full_2_3_5_app_with_tests/public/favicon.ico",
     "test/full_2_3_5_app_with_tests/public/images/rails.png",
     "test/full_2_3_5_app_with_tests/public/index.html",
     "test/full_2_3_5_app_with_tests/public/javascripts/application.js",
     "test/full_2_3_5_app_with_tests/public/javascripts/controls.js",
     "test/full_2_3_5_app_with_tests/public/javascripts/dragdrop.js",
     "test/full_2_3_5_app_with_tests/public/javascripts/effects.js",
     "test/full_2_3_5_app_with_tests/public/javascripts/prototype.js",
     "test/full_2_3_5_app_with_tests/public/robots.txt",
     "test/full_2_3_5_app_with_tests/public/stylesheets/scaffold.css",
     "test/full_2_3_5_app_with_tests/script/about",
     "test/full_2_3_5_app_with_tests/script/console",
     "test/full_2_3_5_app_with_tests/script/dbconsole",
     "test/full_2_3_5_app_with_tests/script/destroy",
     "test/full_2_3_5_app_with_tests/script/generate",
     "test/full_2_3_5_app_with_tests/script/performance/benchmarker",
     "test/full_2_3_5_app_with_tests/script/performance/profiler",
     "test/full_2_3_5_app_with_tests/script/plugin",
     "test/full_2_3_5_app_with_tests/script/runner",
     "test/full_2_3_5_app_with_tests/script/server",
     "test/full_2_3_5_app_with_tests/test/factories.rb",
     "test/full_2_3_5_app_with_tests/test/functional/translations_controller_test.rb",
     "test/full_2_3_5_app_with_tests/test/integration/translation_test.rb",
     "test/full_2_3_5_app_with_tests/test/performance/browsing_test.rb",
     "test/full_2_3_5_app_with_tests/test/selenium.rb",
     "test/full_2_3_5_app_with_tests/test/test_helper.rb",
     "test/full_2_3_5_app_with_tests/test/unit/helpers/translatables_helper_test.rb",
     "test/full_2_3_5_app_with_tests/test/unit/helpers/translations_helper_test.rb",
     "test/full_2_3_5_app_with_tests/test/unit/mongo_translatable_test.rb"
  ]
  s.homepage = %q{http://github.com/kete/mongo_translatable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{MongoDB backed Rails specific I18n model localization meant to tie-in to existing ActiveRecord models}
  s.test_files = [
    "test/full_2_3_5_app_with_tests/app/controllers/application_controller.rb",
     "test/full_2_3_5_app_with_tests/app/controllers/items_controller.rb",
     "test/full_2_3_5_app_with_tests/app/helpers/application_helper.rb",
     "test/full_2_3_5_app_with_tests/app/helpers/items_helper.rb",
     "test/full_2_3_5_app_with_tests/app/models/item.rb",
     "test/full_2_3_5_app_with_tests/config/boot.rb",
     "test/full_2_3_5_app_with_tests/config/environment.rb",
     "test/full_2_3_5_app_with_tests/config/environments/development.rb",
     "test/full_2_3_5_app_with_tests/config/environments/production.rb",
     "test/full_2_3_5_app_with_tests/config/environments/test.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/backtrace_silencers.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/inflections.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/mime_types.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/new_rails_defaults.rb",
     "test/full_2_3_5_app_with_tests/config/initializers/session_store.rb",
     "test/full_2_3_5_app_with_tests/config/routes.rb",
     "test/full_2_3_5_app_with_tests/db/migrate/20100407010602_create_items.rb",
     "test/full_2_3_5_app_with_tests/db/schema.rb",
     "test/full_2_3_5_app_with_tests/db/seeds.rb",
     "test/full_2_3_5_app_with_tests/test/factories.rb",
     "test/full_2_3_5_app_with_tests/test/functional/translations_controller_test.rb",
     "test/full_2_3_5_app_with_tests/test/integration/translation_test.rb",
     "test/full_2_3_5_app_with_tests/test/performance/browsing_test.rb",
     "test/full_2_3_5_app_with_tests/test/selenium.rb",
     "test/full_2_3_5_app_with_tests/test/test_helper.rb",
     "test/full_2_3_5_app_with_tests/test/unit/helpers/translatables_helper_test.rb",
     "test/full_2_3_5_app_with_tests/test/unit/helpers/translations_helper_test.rb",
     "test/full_2_3_5_app_with_tests/test/unit/mongo_translatable_test.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/init.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter/base.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter/force_extension.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter/locale.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter/pagination.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter/uuid_token.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/lib/routing_filter.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/force_extension_spec.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/generation_spec.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/pagination_extension_spec.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/recognition_spec.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/routing_filter_spec.rb",
     "test/full_2_3_5_app_with_tests/vendor/plugins/routing-filter/spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.7.3"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_development_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_development_dependency(%q<webrat>, [">= 0.5.3"])
    else
      s.add_dependency(%q<mongo_mapper>, [">= 0.7.3"])
      s.add_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_dependency(%q<shoulda>, [">= 2.10.3"])
      s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
      s.add_dependency(%q<webrat>, [">= 0.5.3"])
    end
  else
    s.add_dependency(%q<mongo_mapper>, [">= 0.7.3"])
    s.add_dependency(%q<activerecord>, [">= 2.3.5"])
    s.add_dependency(%q<shoulda>, [">= 2.10.3"])
    s.add_dependency(%q<factory_girl>, [">= 1.2.3"])
    s.add_dependency(%q<webrat>, [">= 0.5.3"])
  end
end

